### ISSUE TITLE
Inquiry About Submission Details for Jailbreak Leaderboard

### ISSUE THREAD

**Issue by frank-thou** [TrustAIRLab/Comprehensive_Jailbreak_Assessment#2]
Dear Authors,

First of all, I would like to express my sincere appreciation for your valuable work, which provides significant insights into various aspects of the jailbreak research field.

I noticed that the leaderboard is currently accepting new submissions for jailbreak attack methods. We are the authors of the [DSN](https://github.com/DSN-2024/DSN) attack, which introduces novel optimization-based jailbreak attack along with evaluation methods. Could you please provide more details regarding the submission process, for example, information about the submission format and submission method would be very helpful. This would help makeing a more thorough and comprehensive comparison, allowing to contribute even more valuable insights to the community.

Thank you!

**Comment by Junjie-Chu** [comment]
We have updated the instructions, hope it help.
See [here](https://github.com/TrustAIRLab/Comprehensive_Jailbreak_Assessment/blob/dcb9e7077ae084d69cf1845083b4c68c6e04ef2c/README.md?plain=1#L78-L81).

**Comment by Junjie-Chu** [comment]
I will close the issue. If you have more questions, feel free to open a new one or continue our discuss here.

**Comment by frank-thou** [comment]
Dear Authors,

Apologies for the delayed response. I’ve recently been unexpectedly occupied. Sorry again for my late reply.

I still have some questions and concerns regarding the submission, which I would like to address below.

1. The leaderboard currently supports the ChatGLM3, Llama-2, Vicuna, and black-box models. However, it seems that the optimization-based method (specifically the learning-based method `GCG`) does not yield satisfactory results on the ChatGLM3 model. Rather than the multilingual issue discussed in Section 6.1, I suspect the performance degradation may be related to the conversation template.

    Thus, I would like to clarify whether my submission must include all three of the supported models, or if I can submit only the latter two. Below are my reasons for my doubt.

    First, the chat template plays a critical role in Language Model performance [1]. It is particularly important when it comes to LLM jailbreaking. Based on my experience with jailbreaking the `google/gemma-2-9b-it` model, using the exact default prompt template from the pre-training phase is essential. Specifically, the tokenizer.apply_chat_template() method is crucial. Initially, our implementation used the `fschat` package, which does not support the Gemma conversation template. As a result, I opted to craft and use an unrelated brand-new template to jailbreak gemma, but this led to near-zero performance, implying the Gemma model to be impossible to jailbreak via our method. However, once I switched to the default chat template provided in the tokenizer.apply_chat_template() method, jailbreaking was successful[2].

    More importantly, the default chat templates for ChatGLM3 seem to differ across different resources [3-4]. For example, the HuggingFace and GitHub repositories provide different formats, which could create confusion about the ***true default*** settings and hinder our ability to fairly evaluate our method on the ChatGLM3 model.

2. The uploaded `how_to_submit.md` file suggests to use the same dataset /optimization steps/evaluation method, and late approve us to use our own dataset / evaluation method. Could you kindly clarify the following points?

    2.1. Should our submission be strictly optimized from the `forbidden_question` dataset, and evaluate on the `forbidden_question` dataset, or train from others (e.g. AdvBench) and evaluate on it, or neither train nor evaluate on it. 

    2.2. Given the impotance of chat template, and the fact that different `transformers` package might introduce important and subtle difference on llama-2 chat templates (please refer to section B.1.1 of our paper[2] for detailed explanation), could you please provide detailed demands regarding the testing environment when evaluating our method.

    2.3. The repository also includes a GPT-4 evaluator with tailored prompt. I am wondering whether it would be acceptable to submit our results evaluated by open-source, state-of-the-art methods (e.g., NLI component [2], HarmBench [5], LlamaGuard [6], ShieldGemma [7]) to save on evaluation costs.

3. Lastly, I would like to confirm whether only the markdown file is required for submission, without the inclusion of raw evaluation logs or LLM response results. I am unsure if it would be appropriate to directly upload raw logs via PR, as they may contain harmful responses or jailbreak suffixes. Would it be possible to submit such raw data through a different, secure method to ensure safety, reproducibility, and reliability?

Thank you again for your valuable work and insights. Please feel free to e-mail us at [frank0606thou@gmail.com] or [zhouyk12023@shanghaitech.edu.cn] if you have further concerns or questions.

Best regards,  

---
[1] https://huggingface.co/blog/chat-templates  
[2] Zhou, Yukai, and Wenjie Wang. "Don't Say No: Jailbreaking LLM by Suppressing Refusal." arXiv preprint arXiv:2404.16369 (2024).  
[3] https://huggingface.co/THUDM/chatglm3-6b/discussions/22  
[4] https://github.com/THUDM/ChatGLM3/blob/main/PROMPT.md  
[5] Mazeika, Mantas, et al. "Harmbench: A standardized evaluation framework for automated red teaming and robust refusal." arXiv preprint arXiv:2402.04249 (2024).  
[6] Inan, Hakan, et al. "Llama guard: Llm-based input-output safeguard for human-ai conversations." arXiv preprint arXiv:2312.06674 (2023).  
[7] https://huggingface.co/google/shieldgemma-9b
